const User = require('../models/user');

// Cr√©er un nouvel utilisateur
exports.createUser = async (req, res) => {
  const { name, email, password, role, department } = req.body;

  console.log(req.body); // üîç voir ce que tu re√ßois

  try {
    const newUser = new User({ name, email, password, role, department });
    await newUser.save();
    res.status(201).json(newUser);
  } catch (error) {
    console.error(error); // üîç log plus complet
    res.status(500).json({ message: 'Erreur lors de la cr√©ation de l\'utilisateur', error });
  }
};


// Obtenir tous les utilisateurs
exports.getAllUsers = async (req, res) => {
  try {
    const users = await User.find();
    res.status(200).json(users);
  } catch (error) {
    res.status(500).json({ message: 'Erreur lors de la r√©cup√©ration des utilisateurs', error });
  }
};


exports.loginUser = async (req, res) => {
  const { name, password } = req.body;

  try {
    const user = await User.findOne({ name });

    if (!user) return res.status(404).json({ message: 'Utilisateur non trouv√©' });

    if (user.password !== password) {
      return res.status(401).json({ message: 'Mot de passe incorrect' });
    }

    res.status(200).json({
      id: user._id,
      name: user.name,
      email: user.email,
      role: user.role,
    });
  } catch (err) {
    res.status(500).json({ message: 'Erreur serveur' });
  }
};

exports.updateUser = async (req, res) => {
  try {
    const updatedUser = await User.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true } // renvoie le document modifi√©
    );
    if (!updatedUser) {
      return res.status(404).json({ message: 'Utilisateur non trouv√©' });
    }
    res.json(updatedUser);
  } catch (error) {
    res.status(500).json({ message: 'Erreur lors de la mise √† jour', error });
  }
};

exports.deleteUser = async (req, res) => {
  try {
    await User.findByIdAndDelete(req.params.id);
    res.status(200).json({ message: 'Utilisateur supprim√©' });
  } catch (error) {
    res.status(500).json({ message: 'Erreur lors de la suppression', error });
  }
};